version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - $(aws ecr get-login --no-include-email --region $AWS_REGION )
  build:
    commands:
    - echo Build started on `date`
    - echo Building java
    - cd severity-auditmanagement
    - mvn compile
    - mvn package
    - echo Building the Docker image...
    - docker build -t service/severity-auditmanagement .
    - docker tag service/severity-auditmanagement 421308774925.dkr.ecr.us-east-2.amazonaws.com/auditjwt-registry:severity-auditmanagement
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing the Docker images...
    - docker push 421308774925.dkr.ecr.us-east-2.amazonaws.com/auditjwt-registry:severity-auditmanagement
    - echo Pushing docker image
    - echo Writing image definitions file...
    - printf '[{"name":"severity-auditmanagement-container","imageUri":"%s"}]' 421308774925.dkr.ecr.us-east-2.amazonaws.com/auditjwt-registry:severity-auditmanagement > imagedefinitions.json
artifacts:
  files: severity-auditmanagement/imagedefinitions.json