FROM adoptopenjdk/openjdk11
WORKDIR /
ADD target/severity-auditmanagement-0.0.1-SNAPSHOT.jar severity-auditmanagement-0.0.1-SNAPSHOT.jar
EXPOSE 8082
CMD java -jar severity-auditmanagement-0.0.1-SNAPSHOT.jar