FROM adoptopenjdk/openjdk11
WORKDIR /
ADD target/checklist-auditmanagement-0.0.1-SNAPSHOT.jar checklist-auditmanagement-0.0.1-SNAPSHOT.jar
EXPOSE 8081
CMD java -jar checklist-auditmanagement-0.0.1-SNAPSHOT.jar